
version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build-and-test:  
    docker:
      - image: cimg/node:18.5.0
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run lint
          command: npm run lint
      - run:
          name: Run tests
          command: npm run test:ci
      # persist code coverage report
      - store_artifacts:
          path: coverage
      # persist test report
      - store_test_results:
          path: jest-report


workflows:
  main: 
    jobs:
      - build-and-test
